import type { Language } from "@/lib/types";

export const languages: Language[] = [
  {
    slug: "amharic",
    name: "Amharic",
    nativeName: "አማርኛ",
    scripts: ["Ethiopic"],
    region: "Central and national use",
    family: "Ethio-Semitic",
    status: "available",
    hasAudio: true,
    hasGuidebook: true,
    hasMobileApp: true,
    lessonParts: ["structures", "conversation", "vocabulary", "grammar"],
    summary: "A major Ethiopian language with Ethiopic script learning paths, pronunciation practice, and guidebook support."
  },
  {
    slug: "afaan-oromoo",
    name: "Afaan Oromoo",
    nativeName: "Afaan Oromoo",
    scripts: ["Latin"],
    region: "Oromia and wider Ethiopia",
    family: "Cushitic",
    status: "available",
    hasAudio: true,
    hasGuidebook: true,
    hasMobileApp: true,
    lessonParts: ["structures", "conversation", "vocabulary", "grammar"],
    summary: "A Latin-script learning path with structured lessons, audio examples, and everyday conversation modules."
  },
  {
    slug: "tigrigna",
    name: "Tigrigna",
    nativeName: "ትግርኛ",
    scripts: ["Ethiopic"],
    region: "Tigray and northern Ethiopia",
    family: "Ethio-Semitic",
    status: "available",
    hasAudio: true,
    hasGuidebook: true,
    hasMobileApp: false,
    lessonParts: ["structures", "conversation", "vocabulary", "grammar"],
    summary: "An Ethiopic-script language path designed for pronunciation, grammar confidence, and cultural connection."
  },
  {
    slug: "afar",
    name: "Afar",
    scripts: ["Latin"],
    region: "Afar",
    family: "Cushitic",
    status: "available",
    hasAudio: true,
    hasGuidebook: false,
    hasMobileApp: false,
    lessonParts: ["structures", "conversation", "vocabulary"],
    summary: "A practical starter path for structural phrases, daily conversation, and contextual vocabulary."
  },
  {
    slug: "somali",
    name: "Somali",
    scripts: ["Latin"],
    region: "Somali Region",
    family: "Cushitic",
    status: "available",
    hasAudio: true,
    hasGuidebook: true,
    hasMobileApp: false,
    lessonParts: ["structures", "conversation", "vocabulary", "grammar"],
    summary: "A structured learning path for building communication confidence in a major Horn of Africa language."
  },
  {
    slug: "tambarsa",
    name: "Tambarsa",
    scripts: ["Latin"],
    region: "Southern Ethiopia",
    family: "Other",
    status: "coming-soon",
    hasAudio: false,
    hasGuidebook: false,
    hasMobileApp: false,
    lessonParts: ["structures"],
    summary: "A planned language page prepared for future lessons, audio, and community learning resources."
  },
  {
    slug: "halaba",
    name: "Halaba",
    scripts: ["Latin"],
    region: "Central Ethiopia",
    family: "Highland East Cushitic",
    status: "available",
    hasAudio: true,
    hasGuidebook: false,
    hasMobileApp: false,
    lessonParts: ["structures", "conversation", "vocabulary"],
    summary: "A practical path for structural phrases, conversations, and community-focused language access."
  },
  {
    slug: "sidaamu-afoo",
    name: "Sidaamu Afoo",
    scripts: ["Latin"],
    region: "Sidama",
    family: "Highland East Cushitic",
    status: "available",
    hasAudio: true,
    hasGuidebook: true,
    hasMobileApp: false,
    lessonParts: ["structures", "conversation", "vocabulary", "grammar"],
    summary: "A complete learning direction for structure, conversation, vocabulary, and spoken grammar."
  },
  {
    slug: "wolaita",
    name: "Wolaita",
    scripts: ["Latin"],
    region: "Wolaita",
    family: "Omotic",
    status: "available",
    hasAudio: true,
    hasGuidebook: true,
    hasMobileApp: false,
    lessonParts: ["structures", "conversation", "vocabulary", "grammar"],
    summary: "A learner pathway combining structured lessons, cultural context, and audio support."
  },
  {
    slug: "kabena",
    name: "Kabena",
    scripts: ["Latin"],
    region: "Central Ethiopia",
    family: "Highland East Cushitic",
    status: "coming-soon",
    hasAudio: false,
    hasGuidebook: false,
    hasMobileApp: false,
    lessonParts: ["structures"],
    summary: "A planned language hub prepared for future learning resources and audio validation."
  },
  {
    slug: "mareko",
    name: "Mareko",
    scripts: ["Latin"],
    region: "Central Ethiopia",
    family: "Highland East Cushitic",
    status: "coming-soon",
    hasAudio: false,
    hasGuidebook: false,
    hasMobileApp: false,
    lessonParts: ["structures"],
    summary: "A preservation-first page ready for future translation, review, and publication workflows."
  },
  {
    slug: "awi",
    name: "Awi",
    scripts: ["Ethiopic", "Latin"],
    region: "Agew Awi",
    family: "Cushitic",
    status: "available",
    hasAudio: true,
    hasGuidebook: false,
    hasMobileApp: false,
    lessonParts: ["structures", "conversation", "vocabulary"],
    summary: "A language page for building access to lessons, pronunciation, and script-aware learning."
  },
  {
    slug: "nuer",
    name: "Nuer",
    scripts: ["Latin"],
    region: "Gambella",
    family: "Nilo-Saharan",
    status: "available",
    hasAudio: false,
    hasGuidebook: false,
    hasMobileApp: false,
    lessonParts: ["structures", "conversation"],
    summary: "A language access page for foundational phrases and future expanded learning resources."
  },
];
