// One-time font self-hosting fetch.
// Downloads Noto Sans/Serif Ethiopic woff2 files from Google Fonts into
// public/fonts/ and generates styles/fonts.css with @font-face rules.
// Run: node scripts/fetch-fonts.mjs   (requires network; only needed when fonts change)
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const families = [
  { name: "Noto Sans Ethiopic", slug: "NotoSansEthiopic", weights: [400, 500, 600, 700] },
  { name: "Noto Serif Ethiopic", slug: "NotoSerifEthiopic", weights: [500, 600, 700] }
];

const cssUrl = (f) =>
  `https://fonts.googleapis.com/css2?family=${encodeURIComponent(f.name).replace(/%20/g, "+")}:wght@${f.weights.join(";")}&display=swap`;

// crude but reliable @font-face block parser
function parseFaces(css) {
  const faces = [];
  const re = /@font-face\s*{([^}]*)}/g;
  let m;
  while ((m = re.exec(css))) {
    const body = m[1];
    const pick = (k) => (body.match(new RegExp(k + "\\s*:\\s*([^;]+);")) || [])[1]?.trim();
    const range = pick("unicode-range") || "";
    const label = /comment/.test("") ? "" : "";
    faces.push({
      weight: pick("font-weight"),
      style: pick("font-style") || "normal",
      unicodeRange: range,
      url: (body.match(/url\(([^)]+)\)/) || [])[1]
    });
    void label;
  }
  return faces;
}

// label a face by the comment that precedes it (ethiopic, latin, latin-ext, ...)
function labelFaces(css, faces) {
  const blocks = css.split("@font-face");
  // blocks[0] is preamble; faces[i] corresponds to blocks[i+1], whose comment lives at end of blocks[i]
  return faces.map((f, i) => {
    const before = blocks[i] || "";
    const c = [...before.matchAll(/\/\*\s*([^*]+?)\s*\*\//g)].pop();
    return { ...f, subset: (c ? c[1] : `s${i}`).replace(/[^a-z0-9-]/gi, "") };
  });
}

async function main() {
  await mkdir(resolve(root, "public/fonts"), { recursive: true });
  const cssOut = [
    "/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs. Do not edit by hand. */"
  ];
  let total = 0;

  for (const fam of families) {
    const res = await fetch(cssUrl(fam), { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`CSS fetch failed for ${fam.name}: ${res.status}`);
    const css = await res.text();
    const faces = labelFaces(css, parseFaces(css));

    for (const face of faces) {
      if (!face.url) continue;
      const fname = `${fam.slug}-${face.weight}-${face.subset}.woff2`;
      const bin = await fetch(face.url, { headers: { "User-Agent": UA } });
      if (!bin.ok) throw new Error(`font fetch failed: ${face.url}`);
      await writeFile(resolve(root, "public/fonts", fname), Buffer.from(await bin.arrayBuffer()));
      total++;
      cssOut.push(
        "@font-face {",
        `  font-family: '${fam.name}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        "  font-display: swap;",
        `  src: url('/fonts/${fname}') format('woff2');`,
        ...(face.unicodeRange ? [`  unicode-range: ${face.unicodeRange};`] : []),
        "}"
      );
    }
  }

  await writeFile(resolve(root, "styles/fonts.css"), cssOut.join("\n") + "\n");
  console.log(`Downloaded ${total} woff2 files -> public/fonts/, wrote styles/fonts.css`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
